version: "3.9"

services:

  db:
    image: mysql:8
    container_name: tara-mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: tara
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    container_name: tara-fastapi
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: test
      DB_NAME: tara
      OLLAMA_URL: http://host.docker.internal:11434/api/generate

volumes:
  mysql_data: