version: "3.9"

services:

  db:
    image: mysql:8
    container_name: tara-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    env_file:
      - .env

  api:
    build: .
    container_name: tara-fastapi
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  mysql_data: